/* Japan 2026 — lexicon data module. */
window.JAPAN_LEXICON = [
['Salutations','Bonjour / bonsoir','こんにちは / こんばんは','konnichiwa / konbanwa'],['Salutations','Bonjour (matin)','おはようございます','ohayou gozaimasu'],['Salutations','Au revoir','さようなら','sayounara'],
['Politesse','Merci','ありがとうございます','arigatou gozaimasu'],['Politesse','Merci beaucoup','どうもありがとうございます','doumo arigatou gozaimasu'],['Politesse','S’il vous plaît / je vous en prie','お願いします','onegaishimasu'],['Politesse','Excusez-moi / pardon','すみません','sumimasen'],['Politesse','Désolé','ごめんなさい','gomennasai'],['Politesse','Oui','はい','hai'],['Politesse','Non','いいえ','iie'],['Politesse','D’accord / compris','わかりました','wakarimashita'],['Politesse','Je ne comprends pas','わかりません','wakarimasen'],
['Communication','Parlez-vous anglais ?','英語を話せますか？','eigo o hanasemasu ka?'],['Communication','Je ne parle pas japonais','日本語が話せません','nihongo ga hanasemasen'],['Communication','Pouvez-vous répéter ?','もう一度お願いします','mou ichido onegaishimasu'],['Communication','Pouvez-vous parler plus lentement ?','ゆっくり話してください','yukkuri hanashite kudasai'],['Communication','C’est combien ?','いくらですか？','ikura desu ka?'],['Communication','Où est… ?','…はどこですか？','… wa doko desu ka?'],['Communication','Je voudrais ceci','これをください','kore o kudasai'],['Communication','Pouvez-vous m’aider ?','手伝ってもらえますか？','tetsudatte moraemasu ka?'],
['Restaurant','Menu','メニュー','menyuu'],['Restaurant','Eau','お水','omizu'],['Restaurant','Eau chaude','お湯','oyu'],['Restaurant','Bière','ビール','biiru'],['Restaurant','Thé vert','お茶','ocha'],['Restaurant','Sans viande','肉なし','niku nashi'],['Restaurant','Sans poisson','魚なし','sakana nashi'],['Restaurant','Je suis allergique à…','…にアレルギーがあります','… ni arerugii ga arimasu'],['Restaurant','L’addition, s’il vous plaît','お会計お願いします','okaikei onegaishimasu'],['Restaurant','Délicieux','おいしいです','oishii desu'],['Restaurant','À emporter','持ち帰り','mochikaeri'],['Restaurant','Sur place','店内','tennai'],
['Shopping','Combien ça coûte ?','いくらですか？','ikura desu ka?'],['Shopping','Je regarde seulement','見ているだけです','mite iru dake desu'],['Shopping','Avez-vous une autre taille ?','別のサイズはありますか？','betsu no saizu wa arimasu ka?'],['Shopping','Sac, s’il vous plaît','袋をお願いします','fukuro o onegaishimasu'],['Shopping','Pas de sac, merci','袋はいりません','fukuro wa irimasen'],
['Transport','Gare','駅','eki'],['Transport','Train','電車','densha'],['Transport','Métro','地下鉄','chikatetsu'],['Transport','Bus','バス','basu'],['Transport','Taxi','タクushii','takushii'],['Transport','Billet','切符','kippu'],['Transport','Quai','ホーム','hoomu'],['Transport','Correspondance','乗り換え','norikae'],['Transport','Entrée','入口','iriguchi'],['Transport','Sortie','出口','deguchi'],['Transport','Nord','北','kita'],['Transport','Sud','南','minami'],['Transport','Est','東','higashi'],['Transport','Ouest','西','nishi'],
['Hébergement','Hôtel','ホテル','hoteru'],['Hébergement','Réservation','予約','yoyaku'],['Hébergement','Check-in','チェックイン','chekku-in'],['Hébergement','Check-out','チェックアウト','chekku-auto'],['Hébergement','Bagages','荷物','nimotsu'],['Hébergement','Consigne à bagages','荷物預かり','nimotsu azukari'],
['Pratique','Toilettes','トイレ','toire'],['Pratique','Ouvert','営業中','eigyou-chuu'],['Pratique','Fermé','閉店','heiten'],['Pratique','Aujourd’hui','今日','kyou'],['Pratique','Demain','明日','ashita'],['Pratique','Maintenant','今','ima'],
['Japon','Gare JR','JR駅','JR-eki'],['Japon','Carte Suica','Suica','Suica'],['Japon','Konbini (supérette)','コンビニ','konbini'],['Japon','Distributeur automatique','自動販売機','jidouhanbaiki'],['Japon','Onsen','温泉','onsen'],['Japon','Ryokan','旅館','ryokan'],['Japon','Temple bouddhiste','お寺','otera'],['Japon','Sanctuaire shinto','神社','jinja'],['Japon','Torii','鳥居','torii'],['Japon','Omikuji (prédiction)','おみくじ','omikuji'],['Japon','Omamori (amulette)','お守り','omamori'],['Japon','Attention / danger','危険','kiken'],['Japon','Interdit','禁止','kinshi'],['Japon','Merci pour le repas','ごちそうさまでした','gochisousama deshita'],['Japon','Bon appétit','いただきます','itadakimasu']
];