document.addEventListener("DOMContentLoaded", async () => {
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const slug=v=>String(v||"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9]+/g,"_").replace(/^_+|_+$/g,"").toLowerCase();
  const cityJp={tokyo:"東京",kawaguchiko:"河口湖",kiso:"木曽",kyoto:"京都",hiroshima:"広島",osaka:"大阪"};
  const data=await fetch("./data.json",{cache:"no-store"}).then(r=>r.json());
  const base=typeof places!=="undefined"?places:{};
  const extra=typeof PLANNING_PLACES!=="undefined"?PLANNING_PLACES:{};
  const more=typeof PLANNING_PLACES_MORE!=="undefined"?PLANNING_PLACES_MORE:{};
  const allPlaces={...base,...extra,...more};
  let selectedDate=data.schedule[0]?.date;
  let selectedPlanningCity=data.schedule[0]?.cityKey||"tokyo";
  let currentCity=null;
  let mapChoice=localStorage.getItem("japan2026-map");
  let pendingPlace=null;
  const page=k=>document.querySelector(`.top-page[data-page="${k}"]`);
  const nav=[...document.querySelectorAll(".nav-item")];
  const citiesIndex=document.getElementById("cities-index-view"),cityDetail=document.getElementById("city-detail-view");
  const placeByName=name=>{if(!name)return null;return allPlaces[slug(name)]||Object.values(allPlaces).find(p=>p.name===name)||null};
  const theme=()=>data.cities[selectedPlanningCity]?.theme||"tokyo";
  const setTheme=t=>document.body.dataset.theme=t||"tokyo";
  const restoreTheme=()=>{if(!currentCity)setTheme(theme())};

  function go(k,push=true){if(!page(k))return;if(push)history.pushState({page:k,city:null},"",`#${k}`);page(k).scrollIntoView({behavior:"smooth",inline:"start",block:"nearest"});nav.forEach(n=>n.classList.toggle("active",n.dataset.page===k));}
  nav.forEach(n=>n.addEventListener("click",()=>{if(n.dataset.page==="cities"&&!cityDetail.classList.contains("hidden"))showCities(false);go(n.dataset.page)}));
  document.getElementById("app-shell").addEventListener("touchend",e=>{const t=e.changedTouches[0];if(t.clientX<28){const start=window.__sx||t.clientX;if(t.clientX-start>70)history.back()}},{passive:true});
  document.getElementById("app-shell").addEventListener("touchstart",e=>window.__sx=e.changedTouches[0].clientX,{passive:true});

  function cat(p){const n=p.name.toLowerCase();if(p.category==="hotel")return["Hébergements",n.includes("ryokan")?"Ryokan":n.includes("guest")?"Guest House":"Hôtel"];if(p.category==="restaurant")return["Restaurants",n.includes("ramen")?"Ramen":n.includes("sushi")?"Sushi":/matcha|tsujiri|arabica/.test(n)?"Café / Thé":n.includes("okonomiyaki")?"Okonomiyaki":"Restaurant"];if(p.category==="shopping")return["Shopping",/camera|yodobashi|nintendo|gigo/.test(n)?"Culture & Électronique":/uniqlo|kinji|chicago|mode off/.test(n)?"Mode":"Boutique"];return["Lieux",subcat(p.name,p.category)]}
  function subcat(name,category){const n=name.toLowerCase();if(/shrine|jinja|jingu|inari|taisha/.test(n))return"Sanctuaire";if(/temple|dera|-ji|ji$|kōdai|zojo/.test(n))return"Temple";if(/museum|musée/.test(n))return"Musée";if(/park|parc|garden|jardin|forest|forêt|hill|pavilion/.test(n))return"Jardin / Nature";if(/station|gare|ferry|teleph|téléph/.test(n))return"Transport";if(/street|yokocho|district|crossing|ginza|shibuya|shinjuku|akihabara|naramachi|odaiba/.test(n))return"Quartier / Rue";if(/tower|château|castle|building|sky/.test(n))return"Monument / Vue";return category==="nature"?"Jardin / Nature":"Visite"}
  function area(p,c){const n=p.name.toLowerCase();if(c==="tokyo"){if(/shibuya|hachiko|tower records|parco|harajuku|takeshita|harry potter|yoyogi/.test(n))return"Shibuya / Harajuku";if(/shinjuku|kabukicho|golden gai|omoide|yodobashi|map camera|metropolitan|batting/.test(n))return"Shinjuku";if(/asakusa|senso|nakamise/.test(n))return"Asakusa";if(/yanaka|nezu|ueno|yamashiroya|edo-tokyo/.test(n))return"Yanaka / Nezu / Ueno";if(/akihabara|gigo/.test(n))return"Akihabara";if(/ginza|uniqlo/.test(n))return"Ginza";if(/oimachi/.test(n))return"Oimachi";if(/teamlab|azabudai|zojo|shiba|tokyo tower/.test(n))return"Tokyo Tower / Azabudai";if(/odaiba|unicorn/.test(n))return"Odaiba";return"Tokyo / Autres"}if(c==="kyoto"){if(/arashiyama|sagano|tenryu|togets|yusai|jōjakk|gio|adashino|otagi/.test(n))return"Arashiyama";if(/kiyomizu|ninen|yasaka|maruyama|sanjūsangen|eikan|gion|ginkaku|philosophie/.test(n))return"Higashiyama / Gion";if(/nara|tōdai|kasuga|yoshiki|naramachi|kōfuku|wakakusa|parc de nara/.test(n))return"Nara";if(/fushimi|tofuku/.test(n))return"Fushimi";if(/nijo|kinkaku|kitano|nishiki|ichihara|gare de kyoto/.test(n))return"Centre / Nord de Kyoto";return"Kyoto / Autres"}if(c==="hiroshima")return/miyajima|itsukushima|daish|misen|torii|momiji|anago|kaki/.test(n)?"Miyajima":"Hiroshima";if(c==="osaka"){if(/doton|hozenji|namba/.test(n))return"Namba / Dotonbori";if(/shinsekai|tsūten|tsuten/.test(n))return"Shinsekai";if(/umeda/.test(n))return"Umeda";if(/osaka|cupnoodles/.test(n))return"Osaka Castle / Ikeda";return"Osaka / Autres"}return null}

  function openMap(p){if(!p||p.lat==null)return;if(!mapChoice){pendingPlace=p;document.getElementById("maps-choice-overlay").classList.add("active");return}const url=mapChoice==="apple"?`https://maps.apple.com/?q=${encodeURIComponent(p.name)}&ll=${p.lat},${p.lng}`:`https://www.google.com/maps/search/?api=1&query=${p.lat},${p.lng}(${encodeURIComponent(p.name)})`;window.location.href=url}
  const overlay=document.getElementById("maps-choice-overlay");document.getElementById("maps-choice-close").onclick=()=>{overlay.classList.remove("active");pendingPlace=null};document.querySelectorAll(".map-choice").forEach(b=>b.onclick=()=>{mapChoice=b.dataset.mapChoice;localStorage.setItem("japan2026-map",mapChoice);const p=pendingPlace;overlay.classList.remove("active");pendingPlace=null;if(p)openMap(p)});

  function itinerary(){document.getElementById("timeline-list").innerHTML=data.itinerary.map(s=>`<button class="journey-stop" data-city="${esc(s.cityKey)}" type="button"><span class="journey-rail" style="border-color:var(--${s.cityKey})"></span><span class="journey-date">${esc(s.dates)}</span><span class="journey-city" style="color:var(--${s.cityKey})">${esc(s.label)}</span><span class="journey-jp">${cityJp[s.cityKey]}</span><span class="journey-vibe">${esc(data.cities[s.cityKey].vibe)}</span><span class="journey-arrow">›</span></button>`).join("");document.querySelectorAll(".journey-stop").forEach(b=>b.onclick=()=>showCity(b.dataset.city))}

  function tickets(){document.getElementById("city-tickets").innerHTML=Object.entries(data.cities).map(([k,c])=>`<button class="city-ticket" data-city="${k}" style="--ticket-city:var(--${k})" type="button"><span class="ticket-notch ticket-notch-left"></span><span class="ticket-notch ticket-notch-right"></span><span class="ticket-route">JAPON 2026 · ÉTAPE</span><span class="ticket-city">${esc(c.name)}</span><span class="ticket-jp">${cityJp[k]}</span><span class="ticket-dates">${esc(c.dates)}</span><span class="ticket-mark">›</span></button>`).join("");document.querySelectorAll(".city-ticket").forEach(b=>b.onclick=()=>showCity(b.dataset.city))}

  function specialties(k){const a=data.culinarySpecialties?.[k]||[];if(!a.length)return"";return`<section class="city-block"><div class="section-kicker">Spécialités culinaires</div><div class="specialty-list">${a.map(([n,d])=>`<button class="specialty-row" aria-expanded="false" type="button"><span><strong>${esc(n)}</strong><span class="specialty-description">${esc(d)}</span></span><span class="specialty-arrow">›</span></button>`).join("")}</div></section>`}
  function showCity(k,push=true){currentCity=k;setTheme(data.cities[k].theme);document.getElementById("current-city-title").textContent=data.cities[k].name;document.getElementById("current-city-jp").textContent=cityJp[k];document.getElementById("current-city-vibe").textContent=data.cities[k].vibe;document.getElementById("current-city-dates").textContent=data.cities[k].dates;let html=specialties(k),groups={};Object.values(allPlaces).filter(p=>p.city===k).forEach(p=>{const [g,s]=cat(p),a=area(p,k)||"_root";(groups[a]??={});(groups[a][g]??={});(groups[a][g][s]??=[]).push(p)});Object.keys(groups).sort((a,b)=>a==="_root"?-1:b==="_root"?1:a.localeCompare(b)).forEach(a=>{if(a!=="_root")html+=`<div class="area-heading">${esc(a)}</div>`;["Hébergements","Lieux","Restaurants","Shopping"].forEach(g=>{if(!groups[a][g])return;html+=`<section class="city-block"><div class="section-kicker">${g}</div>`;Object.keys(groups[a][g]).sort().forEach(s=>{if(g==="Lieux")html+=`<div class="subcategory-label">${esc(s)}</div>`;html+=`<div class="place-list">${groups[a][g][s].map(p=>`<button class="place-row" data-place-id="${p.id}" type="button"><span class="place-row-main"><span class="place-name">${esc(p.name)}</span><span class="place-subcategory">${esc(s)}</span></span><span class="place-indicator">›</span></button>`).join("")}</div>`});html+=`</section>`})});document.getElementById("city-categories").innerHTML=html;document.getElementById("city-categories").querySelectorAll(".place-row").forEach(b=>b.onclick=()=>openMap(allPlaces[b.dataset.placeId]));document.getElementById("city-categories").querySelectorAll(".specialty-row").forEach(b=>b.onclick=()=>b.classList.toggle("open"));citiesIndex.classList.add("hidden");cityDetail.classList.remove("hidden");if(push)history.pushState({page:"cities",city:k},"",`#cities/${k}`);go("cities",false)}
  function showCities(push=true){currentCity=null;cityDetail.classList.add("hidden");citiesIndex.classList.remove("hidden");restoreTheme();if(push)history.pushState({page:"cities",city:null},"","#cities");go("cities",false)}
  document.getElementById("city-back").onclick=()=>history.back();

  function renderPlanning(){const d=data.schedule.find(x=>x.date===selectedDate);if(!d)return;selectedPlanningCity=d.cityKey;restoreTheme();const c=data.cities[d.cityKey];document.getElementById("planning-head").innerHTML=`<div class="planning-location">${esc(c.name)}</div><h2>${new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"long"}).format(new Date(`${d.date}T12:00:00`))}</h2><p>${esc(d.title)}</p>`;const slots=["Matin","Midi","Après-midi","Fin d'après-midi","Soirée"];document.getElementById("planning-container").innerHTML=slots.map(slot=>{const items=d.items.filter(x=>x.slot===slot);if(!items.length)return"";return`<section class="planning-slot"><div class="slot-label">${slot}</div><div class="slot-line">${items.map((x,i)=>{if(x.transport)return`<div class="schedule-connector" style="--transport-color:var(--${d.cityKey})"><span class="connector-line"></span><span class="connector-symbol">◇</span><span class="connector-mode">${esc(x.transport.mode)}</span><span class="connector-duration">${esc(x.transport.duration||"")}</span></div>`;const p=placeByName(x.place),pois=(x.pois||[]).map(placeByName).filter(Boolean);return`<article class="schedule-card" style="--city-color:var(--${d.cityKey})"><button class="schedule-summary" aria-expanded="false" type="button"><span class="schedule-time">${esc(x.time||"")}</span><span class="schedule-title">${esc(x.label)}</span><span class="schedule-chevron">›</span></button><div class="schedule-details"><div class="schedule-detail-text">${x.description?esc(x.description):""}</div>${pois.length?`<div class="poi-list">${pois.map(q=>`<button class="poi-link" data-place-id="${q.id}" type="button">${esc(q.name)} <span>›</span></button>`).join("")}</div>`:""}${p?`<div class="schedule-map-row"><button class="schedule-map" data-place-id="${p.id}" type="button">Ouvrir dans ${mapChoice==="apple"?"Plans":mapChoice==="google"?"Google Maps":"Plans / Maps"}</button></div>`:""}</div></article>`}).join("")}</div></section>`}).join("");document.querySelectorAll(".schedule-summary").forEach(b=>b.onclick=()=>{const card=b.closest(".schedule-card");card.classList.toggle("open");b.setAttribute("aria-expanded",card.classList.contains("open"))});document.querySelectorAll("[data-place-id]").forEach(b=>{if(!b.classList.contains("place-row"))b.onclick=()=>openMap(allPlaces[b.dataset.placeId])})}
  function planningDays(){const strip=document.getElementById("day-strip");strip.innerHTML=data.schedule.map(d=>`<button class="day-choice ${d.date===selectedDate?"active":""}" data-date="${d.date}" type="button"><span>${new Intl.DateTimeFormat("fr-FR",{weekday:"short"}).format(new Date(`${d.date}T12:00:00`)).replace(".","")}</span><strong>${new Date(`${d.date}T12:00:00`).getDate()}</strong></button>`).join("");strip.querySelectorAll("button").forEach(b=>b.onclick=()=>{selectedDate=b.dataset.date;currentCity=null;planningDays();renderPlanning()})}

  function lexicon(){const target=document.getElementById("lexicon-container"),input=document.getElementById("lexicon-search");const draw=()=>{const q=input.value.toLowerCase();target.innerHTML=data.lexicon.filter(x=>x.join(" ").toLowerCase().includes(q)).map(x=>`<div class="lexicon-row"><div><span class="lex-fr">${esc(x[1])}</span><span class="lex-cat">${esc(x[0])}</span></div><span class="lex-jp">${esc(x[2])}</span></div>`).join("")};input.oninput=draw;draw()}
  async function exchange(){let rate=data.defaultExchangeRate||165;const info=document.getElementById("rate-info-text");try{const r=await fetch("https://api.frankfurter.dev/v1/latest?base=EUR&symbols=JPY");const x=await r.json();if(x.rates?.JPY)rate=x.rates.JPY;info.textContent=`Dernier taux publié · 1 € = ${rate.toFixed(2)} ¥ · ${x.date}`}catch{info.textContent=`Taux de secours · 1 € = ${rate.toFixed(2)} ¥`}const j=document.getElementById("jpy-input"),e=document.getElementById("eur-input");j.oninput=()=>{e.value=(Number(j.value)/rate).toFixed(2)};e.oninput=()=>{j.value=(Number(e.value)*rate).toFixed(0)}}
  document.getElementById("map-setting")?.addEventListener("click",()=>{pendingPlace=null;overlay.classList.add("active")});
  window.addEventListener("popstate",e=>{if(e.state?.page==="cities"&&e.state.city)showCity(e.state.city,false);else if(e.state?.page==="cities")showCities(false);else restoreTheme()});
  itinerary();tickets();planningDays();renderPlanning();lexicon();exchange();restoreTheme();
});
