document.addEventListener("DOMContentLoaded", async () => {
let appData=null,currentCityKey="tokyo",exchangeRate=165.0;if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(console.error);try{const r=await fetch("./data.json");appData=await r.json();exchangeRate=appData.defaultExchangeRate||165}catch(e){console.error(e);return}
const swipe=document.getElementById("swipe-container"),dots=document.querySelectorAll("#dots-container .dot"),pages=Array.from(document.querySelectorAll(".tab-page"));const go=i=>pages[i]?.scrollIntoView({behavior:"smooth",inline:"start",block:"nearest"});const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));swipe.addEventListener("scroll",()=>{const i=Math.round(swipe.scrollLeft/window.innerWidth);dots.forEach((d,n)=>d.classList.toggle("active",n===i))});dots.forEach(d=>d.addEventListener("click",()=>go(+d.dataset.index)));
const meta={hotel:["🏨 Hébergement",1],activity:["⛩️ Visites & Activités",2],restaurant:["🍜 Restaurants",3],shopping:["🛍️ Shopping",4],museum:["🏛️ Musées",5],nature:["🌿 Parcs & Nature",6],transport:["🚉 Transports",7]};const map=p=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${p.name} ${p.lat},${p.lng}`)}`;
function city(k){currentCityKey=k;const c=appData.cities[k];if(!c)return;document.body.dataset.theme=c.theme||"tokyo";document.getElementById("current-city-title").textContent=c.name;document.getElementById("current-city-vibe").textContent=c.vibe;document.getElementById("current-city-dates").textContent=c.dates;document.querySelectorAll("#city-pills .pill").forEach(p=>p.classList.toggle("active",p.dataset.city===k));const g=Object.values(places).filter(p=>p.city===k).reduce((a,p)=>{(a[p.category]??=[]).push(p);return a},{}),cats=Object.keys(g).sort((a,b)=>(meta[a]?.[1]??99)-(meta[b]?.[1]??99));document.getElementById("city-categories").innerHTML=cats.map(x=>`<h3 class="section-title">${meta[x]?.[0]||esc(x)}</h3><div class="card details-card">${g[x].map(p=>`<div class="detail-row"><div class="detail-left"><span class="place-name">${esc(p.name)}</span></div><a href="${map(p)}" target="_blank" rel="noopener" class="chevron">📍</a></div>`).join("")}</div>`).join("")}
function pills(){const c=document.getElementById("city-pills");c.innerHTML=Object.entries(appData.cities).map(([k,v])=>`<button class="pill ${k===currentCityKey?'active':''}" data-city="${k}">${esc(v.name)}</button>`).join("");c.querySelectorAll(".pill").forEach(p=>p.addEventListener("click",()=>city(p.dataset.city)))}
function timeline(){const c=document.getElementById("timeline-list");c.innerHTML=(appData.itinerary||[]).map(s=>{const v=appData.cities[s.cityKey];return`<div class="timeline-item" data-city="${esc(s.cityKey)}"><div class="timeline-left"><span class="timeline-icon">${esc(v.icon)}</span><div class="timeline-info"><span class="city-title">${esc(s.label)}</span><span class="city-dates">${esc(s.dates)}</span></div></div><span class="vibe-badge">${esc(v.vibe.split("/")[0])}</span></div>`}).join("");c.querySelectorAll(".timeline-item").forEach(x=>x.addEventListener("click",()=>{city(x.dataset.city);go(3)}))}
function today(){const d=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()),s=(appData.schedule||[]).find(x=>x.date===d),c=document.getElementById("today-schedule-container");if(!s){document.getElementById("today-title").textContent="Aucune activité prévue";document.getElementById("today-subtitle").textContent="Profitez de votre journée libre !";c.innerHTML=`<div class="card"><p class="place-desc">Aucun événement programmé à la date du jour.</p></div>`;return}document.getElementById("today-title").textContent=s.title;document.getElementById("today-subtitle").textContent=appData.cities[s.cityKey]?.name||"";c.innerHTML=`<div class="card details-card">${s.items.map(i=>`<div class="detail-row"><div class="detail-left"><span class="place-name">${esc(i.label)}</span><span class="place-desc">${esc(i.time)}</span></div></div>`).join("")}</div>`}
const j=document.getElementById("jpy-input"),e=document.getElementById("eur-input"),ri=document.getElementById("rate-info-text");async function rate(){let d=null;try{const x=JSON.parse(localStorage.getItem("japan_rate_cache"));exchangeRate=x.rate;d=new Date(x.timestamp)}catch{}if(navigator.onLine)try{const a=new AbortController(),t=setTimeout(()=>a.abort(),3000),r=await fetch("https://open.er-api.com/v6/latest/EUR",{signal:a.signal});clearTimeout(t);if(r.ok){const x=await r.json();if(x?.rates?.JPY){exchangeRate=x.rates.JPY;d=new Date;localStorage.setItem("japan_rate_cache",JSON.stringify({rate:exchangeRate,timestamp:d.toISOString()}))}}}catch{}ri.textContent=d?`Taux direct (${d.toLocaleDateString("fr-FR",{day:"2-digit",month:"2-digit"})} à ${d.toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"})}) : 1 € = ${exchangeRate.toFixed(2)} ¥`:`Taux par défaut : 1 € = ${exchangeRate.toFixed(2)} ¥`};j.addEventListener("input",()=>{const v=parseFloat(j.value);e.value=Number.isNaN(v)?"":(v/exchangeRate).toFixed(2)});e.addEventListener("input",()=>{const v=parseFloat(e.value);j.value=Number.isNaN(v)?"":Math.round(v*exchangeRate)});
const lex=document.getElementById("lexicon-container"),search=document.getElementById("lexicon-search");function lexicon(f=""){f=f.toLowerCase();lex.innerHTML=(appData.lexicon||[]).filter(x=>x.fr.toLowerCase().includes(f)||x.jp.toLowerCase().includes(f)).map(x=>`<div class="lexicon-item"><span class="lex-fr">${esc(x.fr)} (${esc(x.cat)})</span><span class="lex-jp">${esc(x.jp)}</span></div>`).join("")}search.addEventListener("input",x=>lexicon(x.target.value));pills();today();timeline();city("tokyo");lexicon();await rate();go(2);
});
